# Generated by Django 3.1 on 2021-04-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210404_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
